# VIGIL Configuration File
logging:
  level: INFO
  name: vigil
  file: logs/vigil.log
  file_level: DEBUG
  file_overwrite: true   # Overwrite log file on startup (true) or append (false)
  console: true
  console_level: INFO

crawler:
  user_agent: "Mozilla/5.0 (X11; Linux i686; rv:137.0) Gecko/20100101 Firefox/137.0"
  timeout: 30
  delay: 1.5
  max_retries: 3
  max_depth: 2
  max_urls: 50
  max_queue_size: 1000  # Maximum size of URL queue to prevent memory issues
  output_dir: "crawled_data"
  start_urls:
    - "https://thehackernews.com/"
    - "https://gbhackers.com/"
    - "https://securityledger.com/"
    - "https://www.itsecurityguru.org/"
    - "https://www.bleepingcomputer.com/"
    - "https://securityboulevard.com/security-creators-network/"
    - "https://krebsonsecurity.com/"
  allowed_domains:
    - "thehackernews.com"
    - "www.bleepingcomputer.com"
    - "krebsonsecurity.com"

model:
  path: "dataset/dataset-20250403-141226/models/logistic_regression-20250403-141246.pkl"  # Directly specify model path
  vectorizer_path: "dataset/dataset-20250403-141226/vectorizer.pkl"  # Add vectorizer path
  confidence_threshold: 0.6             # Threshold for classification

storage:
  file_store_path: "data"
  db_path: "data/vigil_data.db"  # This should be a path in a directory that exists or can be created
  auto_save: true    # Automatically save crawled content to the database
  auto_export: true  # Automatically export data after crawling
  export_format: "json"

scheduler:
  db_path: "database-workflow/scheduler.db"  # Separate database for scheduler
  job_store_path: "database-workflow/jobs.json"  # Path to store job information (legacy)
  jobs:
    - id: "minutes-thehackernews"
      url: "https://thehackernews.com/"
      interval_minutes: 10  # every 10 mins
      max_urls: 50    
    - id: "minutes-gbhackers"
      url: "https://gbhackers.com/"
      interval_minutes: 10  # every 10 mins
      max_urls: 50
    - id: "minutes-securityledger"
      url: "https://securityledger.com/"
      interval_minutes: 10  # every 10 mins
      max_urls: 50
    - id: "minutes-itsecurityguru"
      url: "https://www.itsecurityguru.org/"
      interval_minutes: 10  # every 10 mins
      max_urls: 50
    - id: "minutes-securityboulevard"
      url: "https://securityboulevard.com/security-creators-network/"
      interval_minutes: 10  # every 10 mins
      max_urls: 50
    - id: "minutes-krebsonsecurity"
      url: "https://krebsonsecurity.com/"
      interval_minutes: 10  # every 10 mins
      max_urls: 50
    - id: "minutes-bleeping"
      url: "https://www.bleepingcomputer.com/"
      interval_minutes: 5  # Weekly
      max_urls: 50
